//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deleted_DSROCartons
    {
        public int CartonDeleteID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CartonID { get; set; }
        public string CartonDescription { get; set; }
        public int CartonNewID { get; set; }
        public string CrowRefID { get; set; }
        public Nullable<int> DSROID { get; set; }
        public int LocationID { get; set; }
        public bool Dispatched { get; set; }
        public bool CartonCanmove { get; set; }
        public string LocationNumber { get; set; }
        public int CartonSize { get; set; }
        public string CartonDetails { get; set; }
        public string Remark { get; set; }
        public string UserControl { get; set; }
    }
}
