//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSCartonMovementDetail
    {
        public int DSCartonMovementDetailID { get; set; }
        public Nullable<int> DSCartonMovementID { get; set; }
        public Nullable<int> CartonID { get; set; }
    
        public virtual DSCartonMovement DSCartonMovement { get; set; }
    }
}
