//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSCartonStockOnHandDaily
    {
        public int ReportDateID { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<float> Volume { get; set; }
    }
}
