//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSCartonCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSCartonCategory()
        {
            this.DSCartonsNews = new HashSet<DSCartonsNew>();
        }
    
        public int DSCartonCategoryID { get; set; }
        public int DSCustomerID { get; set; }
        public string CategoryDescription { get; set; }
        public string CategoryDescriptionVietnam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSCartonsNew> DSCartonsNews { get; set; }
    }
}
