//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSCartonMovement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSCartonMovement()
        {
            this.DSCartonMovementDetails = new HashSet<DSCartonMovementDetail>();
        }
    
        public int DSCartonMovementID { get; set; }
        public string SourceLocationNumber { get; set; }
        public string DestinationLocationNumber { get; set; }
        public Nullable<System.DateTime> DateMovement { get; set; }
        public string ReasonMovement { get; set; }
        public string AuthorisedBy { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSCartonMovementDetail> DSCartonMovementDetails { get; set; }
    }
}
