//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSCartonStockOnHandMonthly
    {
        public int MonthDateID { get; set; }
        public Nullable<System.DateTime> MonthDate { get; set; }
        public Nullable<int> CartonStock { get; set; }
        public Nullable<int> CustomerID { get; set; }
    }
}
