//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSCartonsNew
    {
        public int CartonNewID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int CartonID { get; set; }
        public bool CartonSelected { get; set; }
        public string CustomerRef { get; set; }
        public string CrowRefID { get; set; }
        public bool CartonReturned { get; set; }
        public float CartonSize { get; set; }
        public string CartonDetails { get; set; }
        public Nullable<int> DSReceivingOrderID { get; set; }
        public Nullable<bool> CartonPrint { get; set; }
        public Nullable<System.DateTime> DestructionDate { get; set; }
        public int DSCartonCategoryID { get; set; }
        public byte[] tmp { get; set; }
        public string UpdatedBy { get; set; }
        public bool CheckSelected { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual DSCartonCategory DSCartonCategory { get; set; }
    }
}
