//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSDOCarton
    {
        public int DispatchedCartonID { get; set; }
        public int DSDOID { get; set; }
        public string CartonDescription { get; set; }
        public string CrowRefID { get; set; }
        public int CartonID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string LocationNumber { get; set; }
        public byte[] ts { get; set; }
        public Nullable<bool> CheckSelectDelete { get; set; }
        public string Remark { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual DSDispatchingOrder DSDispatchingOrder { get; set; }
        public virtual DSLocation DSLocation { get; set; }
    }
}
