//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSLocation()
        {
            this.DSDOCartons = new HashSet<DSDOCarton>();
            this.DSROCartons = new HashSet<DSROCarton>();
        }
    
        public int LocationID { get; set; }
        public string LocationNumber { get; set; }
        public string RoomID { get; set; }
        public bool Used { get; set; }
        public Nullable<byte> LocationCode { get; set; }
        public Nullable<short> Aisle { get; set; }
        public Nullable<short> Bay { get; set; }
        public Nullable<short> High { get; set; }
        public Nullable<short> Deep { get; set; }
        public Nullable<byte> StandardCarton { get; set; }
        public Nullable<int> Referent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSDOCarton> DSDOCartons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSROCarton> DSROCartons { get; set; }
    }
}
