//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSROCarton
    {
        public int CartonID { get; set; }
        public string CartonDescription { get; set; }
        public int CartonNewID { get; set; }
        public int DSROID { get; set; }
        public int LocationID { get; set; }
        public bool CartonCanmove { get; set; }
        public string LocationNumber { get; set; }
        public float CartonSize { get; set; }
        public string CartonDetails { get; set; }
        public string CrowRefID { get; set; }
        public Nullable<System.DateTime> DestructionDate { get; set; }
        public int DSCartonCategoryID { get; set; }
        public bool CheckDelete { get; set; }
        public byte[] ts { get; set; }
        public Nullable<bool> Dispatched { get; set; }
        public Nullable<bool> CheckSelectDispatched { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> ScannedTime { get; set; }
        public string ScannedUser { get; set; }
        public string SealNumber { get; set; }
    
        public virtual DSLocation DSLocation { get; set; }
        public virtual DSReceivingOrder DSReceivingOrder { get; set; }
    }
}
