//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.RequestCartons = new HashSet<RequestCarton>();
        }
    
        public int RequestID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public bool EmtyCarton { get; set; }
        public bool DocumentRetrieval { get; set; }
        public bool CartonDestruction { get; set; }
        public bool OnSiteChecking { get; set; }
        public string RequestDescription { get; set; }
        public string DeliveryAddress { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public int RequestQuantity { get; set; }
        public byte RequestStatus { get; set; }
        public string ProcessBy { get; set; }
        public Nullable<System.DateTime> ProcessTime { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> ReferenceOrderID { get; set; }
        public bool FileUploaded { get; set; }
        public string FileUploadedCode { get; set; }
        public string ProcessFeedback { get; set; }
        public string RequestType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestCarton> RequestCartons { get; set; }
    }
}
