//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestCarton
    {
        public int RequestCartonID { get; set; }
        public int RequestID { get; set; }
        public Nullable<int> CartonID { get; set; }
        public string Remark { get; set; }
        public int CartonNewID { get; set; }
        public string CartonReference { get; set; }
        public string CartonReference2 { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
