//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpAttachment
    {
        public int AttachmentID { get; set; }
        public int CheckingID { get; set; }
        public string AttachmentDescription { get; set; }
        public string AttachmentFile { get; set; }
        public System.DateTime AttachmentDate { get; set; }
        public string AttachmentUser { get; set; }
        public byte[] TS { get; set; }
        public Nullable<int> AttachmentFileSize { get; set; }
        public string OriginalFileName { get; set; }
        public Nullable<bool> CheckingUpdate { get; set; }
        public string LocationChecking { get; set; }
        public string CheckingType { get; set; }
    }
}
