//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpBillingReport
    {
        public int BillingDateID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public int BeginC { get; set; }
        public double BeginW { get; set; }
        public int InC { get; set; }
        public double InW { get; set; }
        public int OutC { get; set; }
        public double OutW { get; set; }
        public int CloseC { get; set; }
        public double CloseW { get; set; }
        public int CustomerID { get; set; }
        public Nullable<double> BeginP { get; set; }
        public Nullable<double> InP { get; set; }
        public Nullable<double> OutP { get; set; }
        public Nullable<double> CloseP { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    }
}
