//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpDSOrdersUpdate
    {
        public int Id { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<bool> OrderCheck { get; set; }
        public byte[] ts { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    }
}
