//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpNoteDispatchingOder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmpNoteDispatchingOder()
        {
            this.tmpNoteDispatchingOderDetails = new HashSet<tmpNoteDispatchingOderDetail>();
        }
    
        public int NoteDispatchingOderID { get; set; }
        public string NoteDispatchingOderNumber { get; set; }
        public Nullable<int> DispatchingOderID { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> NoteDate { get; set; }
        public string NoteBy { get; set; }
        public Nullable<bool> Checked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmpNoteDispatchingOderDetail> tmpNoteDispatchingOderDetails { get; set; }
    }
}
