//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Customers
    {
        public int CustomerID { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public string Initial { get; set; }
        public string Address { get; set; }
        public string CustomerType { get; set; }
        public string PrimaryContact { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Fax2 { get; set; }
        public string Email { get; set; }
        public string OtherContacts { get; set; }
        public string MarketingInfor { get; set; }
        public string CustomerInvoiceName { get; set; }
        public string CustomerInvoiceAddress { get; set; }
        public string CustomerInvoiceTaxCode { get; set; }
        public Nullable<bool> CustomerDiscontinued { get; set; }
        public byte CustomerCategory { get; set; }
        public Nullable<byte> CustomerGroup { get; set; }
        public int CustomerMainID { get; set; }
        public Nullable<bool> CustomerByExpiryDate { get; set; }
        public Nullable<bool> SendNote { get; set; }
    }
}
