//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCartonDispatchedLast2days
    {
        public int CartonNewID { get; set; }
        public Nullable<bool> Dispatched { get; set; }
        public string DSCustomerNumber { get; set; }
        public string DSCustomerName { get; set; }
        public System.DateTime DSReceivingOrderDate { get; set; }
        public string CartonDescription { get; set; }
        public System.DateTime DSDispatchingOrderDate { get; set; }
    }
}
