//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ServicesDefinition
    {
        public int ServiceID { get; set; }
        public string ServiceNumber { get; set; }
        public string ServiceName { get; set; }
        public string Measure { get; set; }
        public bool Code { get; set; }
        public Nullable<int> CustomerCategory { get; set; }
        public string ServiceCategory { get; set; }
        public Nullable<double> CheckingQuantityMax { get; set; }
        public Nullable<double> CheckingQuantityMin { get; set; }
        public string ServiceNameVietnamese { get; set; }
    }
}
