//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Employees
    {
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<short> Status { get; set; }
        public string Education { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> DateOfEntry { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string IDCardNumber { get; set; }
        public string Email { get; set; }
        public string Photograph { get; set; }
        public bool Active { get; set; }
        public bool ContractPermanent { get; set; }
        public int ManagementLevel { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string VietnamName { get; set; }
        public string BikeNumber { get; set; }
        public bool BikeUse { get; set; }
        public string VietnamPosition { get; set; }
        public string InOutCardNumber { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<byte> Grade { get; set; }
        public Nullable<byte> Department { get; set; }
        public string AddressNow { get; set; }
        public bool PerformanceStatus { get; set; }
        public Nullable<System.DateTime> IDCardIssueDate { get; set; }
    }
}
